name: Android Feature Branch CI

on:
  pull_request:
    branches:
      - '*'
      - '!master'
      - '!release*'
jobs:
  test:
    name: Run Tests
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      
      - name: Unit tests
        run: bash ./gradlew testDebugUnitTest
      
      - name: Instrumentation Test
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 29
          script: ./gradlew connectedDebugAndroidTest



      
